/// Flutter icons SuperIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SuperIcons
///      fonts:
///       - asset: fonts/SuperIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SuperIcons {
  SuperIcons._();

  static const _kFontFam = 'SuperIcons';
  static const String? _kFontPkg = null;

  static const IconData doublerightarrows = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_pin = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_arrow = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
